version: "3.7"

services:
  db:
    image: mg-postgres
    build: ./postgres
    ports:
      - "5433:5432"
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - "8080:8080"
  express:
    image: mg-server
    build: ./express
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DEBUG: express:*
    volumes:
      - type: bind
        source: ./express
        target: /app
      - /app/node_modules
    ports:
      - "3000:3000"
  next:
    image: mg-next
    build: ./next
    depends_on:
      - db
      - express
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./next
        target: /app
      - /app/node_modules
    ports:
      - "3001:3001"
    command: ["npm", "run", "dev"]
